### ISSUE TITLE
Gig list is not showing all projects that have been created.

### ISSUE THREAD

**Issue by hazmeeeeen** [themuhdhilmi/TestMatrixTicket#10]
Gigs in the list below is showing only 2 of the projects created, while there are actually more.

![gig list is not showing all projects](https://github.com/themuhdhilmi/TestMatrixTicket/assets/164850805/6d7bd23a-4a3b-4361-884b-d734e526030c)

**Comment by themuhdhilmi** [comment]
Only project that has been accepted by admin will be appeared on both carousell and giglist.
It'll be fixed on the next deployment.
