### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by hazmeeeeen** [themuhdhilmi/TestMatrixTicket#7]
The word "aleady" is misspelled. -Should be "already".
![interface- spelling error](https://github.com/themuhdhilmi/TestMatrixTicket/assets/164850805/3a6c0329-a65b-4b9b-af99-e0238b6c7266)
![spelling error](https://github.com/themuhdhilmi/TestMatrixTicket/assets/164850805/6173cb42-9d93-4541-961c-efb0fe6cbccb)

**Comment by themuhdhilmi** [comment]
Will be fix in gig info page revamp
